src/client/pages/HomePage.jsx, src/components/index.js, src/components/molecules/Header/Header.html.TODO, src/components/molecules/Header/Header.jsx, src/components/molecules/Header/Header.jsx.Examples.json, src/components/molecules/Header/Header.pcss
Header component done; with the use of rem function and css media queries with em function.
=> Header component (with mask)

.eslintrc, package.json, src/client/components/CodeSnippet.jsx, src/client/components/FunkyPanel.jsx, src/client/components/FunkyTab.jsx, src/client/pages/ComponentsByTypePage.jsx, src/client/pages/ComponentsPage.jsx, src/client/pages/LayoutPage.jsx, src/client/utils/colorUtil.js, src/components/atoms/ProgressBar/ProgressBar.jsx, src/components/index.js, src/components/molecules/DonutChart/DonutChart.jsx, src/components/molecules/ProgressChart/ProgressChart.jsx, webpack-dev.config.js, webpack-prod.config.js
Hi,
As discussed earlier I set some basic rules that reinforce the current code style. There was a small number of deviations in semicolons and spacing, so i fixed those as well in this PR.
Marek
=> eslint configuration

src/client/pages/BlogSamplePage.jsx, src/client/utils/componentUtil.js, src/components/atoms/RelatedArticle/RelatedArticle.html, src/components/atoms/RelatedArticle/RelatedArticle.md, src/components/atoms/RelatedArticle/RelatedArticle.pcss, src/components/atoms/Tags/Tags.pcss, src/components/ie-hacks.pcss, src/components/molecules/RelatedArticles/RelatedArticles.html, src/components/molecules/RelatedArticles/RelatedArticles.md, src/components/molecules/RelatedArticles/RelatedArticles.pcss
I have made RelatedArticle as an atom and RelatedArticles as a molecule, and added them to the blog sample page.
I also added some ie/edge specific code for the <hr/>.
=> RelatedArticle and RelatedArticles components

src/client/pages/BlogSamplePage.jsx, src/components/atoms/Image/Image.Inline-Left.html, src/components/atoms/Image/Image.Inline-Right.html, src/components/atoms/Image/Image.html, src/components/atoms/Image/Image.md, src/components/atoms/Image/Image.pcss
I'm not quite sure if the bem-naming is good. I want the component to be named something short like "image" to keep the names of the css-classes within the component as short as possible, but then I couldn't come up with a better name than "image__image" to put on the <img/>.. Suggestions? Or is it okay?
=> Image component with caption

src/client/Routes.js, src/components/molecules/PageHeader/PageHeader.jsx, src/components/molecules/PageHeader/PageHeader.jsx.Examples.json, src/components/molecules/PageHeader/PageHeader.pcss
- Use desktop-logo on mobile.
- Change color on other icons to black
=> PageHeader changes

src/components/atoms/Label/Label.jsx, src/components/atoms/Label/Label.jsx.Examples.json, src/components/atoms/Label/Label.pcss, src/components/index.js
We need other form components to be done as well before we say that this component is finished, because we need to show some examples of Label with a form element.
=> Label component first version

src/components/atoms/NumberBoxes/NumberBoxes.3-boxes.html, src/components/atoms/NumberBoxes/NumberBoxes.4-boxes.html, src/components/atoms/NumberBoxes/NumberBoxes.6-boxes.html, src/components/atoms/NumberBoxes/NumberBoxes.pcss
=> NumberBoxes have no horizontal scrolling, but instead have a flexible

src/client/utils/componentUtil.js, src/components/index.js, src/components/molecules/UserDashboard/UserDashboard.jsx, src/components/molecules/UserDashboard/UserDashboard.jsx.Examples.json, src/components/molecules/UserDashboard/UserDashboard.pcss
=> UserDashboard component

src/components/index.js, src/components/molecules/BelowTheLineOffer/BelowTheLineOffer.jsx, src/components/molecules/BelowTheLineOffer/BelowTheLineOffer.jsx.Examples.json, src/components/molecules/BelowTheLineOffer/BelowTheLineOffer.pcss
BelowTheLineOffer component added.
=> BelowTheLineOffer added

src/components/atoms/Button/Button.jsx, src/components/index.js, src/components/molecules/Campaign/Campaign.jsx, src/components/molecules/Campaign/Campaign.jsx.Examples.json, src/components/molecules/Campaign/Campaign.pcss
We anticipate that we will come back to this component and adjust the background image size, once we speak with UX. The task can be reviewed, tested and deployed as it is now, though.
=> Campaign component v1

package-lock.json, src/client/utils/componentUtil.js, src/components/atoms/Button/Button.pcss, src/components/index.js, src/components/molecules/ConfirmChanges/ConfirmChanges.html, src/components/molecules/ConfirmChanges/ConfirmChanges.md, src/components/molecules/ConfirmChanges/ConfirmChanges.pcss, src/components/molecules/ModalDialog/ModalDialog.pcss, src/components/molecules/PopUpLine/PopUpLine.jsx, src/components/molecules/PopUpLine/PopUpLine.jsx.Examples.json, src/components/molecules/PopUpLine/PopUpLine.pcss
- Added static PopUpLine component
- Deleted old ConfirmChanges component since the PopUpLine is the component we will use instead
- Approved by designer
- Updated button--cancel css because styling wasn't relevant when being used in PopUpLine instead of ConfirmChanges
=> PopUpLine component

VERSIONS.md, package.json, src/components/atoms/TelephoneNumberLink/TelephoneNumberLink.html, src/components/atoms/TelephoneNumberLink/TelephoneNumberLink.md, src/components/atoms/TelephoneNumberLink/TelephoneNumberLink.pcss
=> Added TelephoneNumberLink

VERSIONS.md, package.json, src/components/atoms/Label/Label.jsx, src/components/atoms/TextArea/TextArea.md, src/components/atoms/TextArea/TextArea.pcss, src/components/index.js, src/components/molecules/TextAreaWithLabel/TextAreaWithLabel.jsx, src/components/molecules/TextAreaWithLabel/TextAreaWithLabel.jsx.Examples.json, src/components/molecules/TextAreaWithLabel/TextAreaWithLabel.pcss
=> TextArea with the possibility of label

VERSIONS.md, package.json, src/components/atoms/InputError/InputError.html, src/components/atoms/InputError/InputError.md, src/components/atoms/InputError/InputError.pcss, src/components/atoms/TextArea/TextArea.pcss, src/components/atoms/TextArea/TextArea.with-error.html, src/components/molecules/RadioButtonList/RadioButtonWithLabel.pcss, src/components/molecules/TextAreaWithLabel/TextAreaWithLabel.jsx, src/components/molecules/TextAreaWithLabel/TextAreaWithLabel.jsx.Examples.json, src/components/molecules/TextBoxWithLabel/TextBoxWithLabel.jsx, src/components/molecules/TextBoxWithLabel/TextBoxWithLabel.jsx.Examples.json, src/components/molecules/TextBoxWithLabel/TextBoxWithLabel.pcss
Before merging the version needs to be updated. There shouldn't be any breaking changes
=> focusable radios & errors on inputs

README.md, package.json, scripts/export.js
Appears to work fine on Christopher's machine now.
=> Added export script to export styleguide to another project.

src/components/atoms/Button/Button.jsx, src/components/atoms/Button/Button.jsx.Examples.json, src/components/atoms/Button/Button.pcss
We needed a greyed-out disabled button for B2B. I believe it also appears in a few of Ulrikke's prototypes.
=> Created disabled button.

VERSIONS.md, package-lock.json, package.json, src/components/molecules/ProductList/ProductList.jsx, src/components/molecules/ProductList/ProductList.jsx.Examples.json, src/components/molecules/ProductList/ProductList.pcss
Also added focus styling (although improvement is needed)
=> ProductList: Refactored HTML to allow links

src/components/index.js, src/components/molecules/Tooltip/Tooltip.jsx, src/components/molecules/Tooltip/Tooltip.jsx.Examples.json, src/components/molecules/Tooltip/Tooltip.pcss
- Remember to update styleguide version (and perhaps version.md) before merging
=> Tooltip component

component-lib/package.json, component-lib/src/organisms/Form/Form.pcss, package.json
This will fix the following problem I've seen in forms:
=> fix button inside forms

component-lib/src/index.js, component-lib/src/molecules/References/References.jsx, component-lib/src/molecules/References/References.pcss, src/client/examples/molecules/References/References.js
=> references box

component-lib/src/atoms/Button/Button.jsx, component-lib/src/index.js, component-lib/src/molecules/FocusHeader/FocusHeader.jsx, component-lib/src/molecules/FocusHeader/FocusHeader.md, src/client/examples/molecules/FocusHeader/Default.js, src/client/examples/molecules/FocusHeader/FocusHeader.html
Also add missing margin property to Button, since it's used in the example.
=> FocusHeader component

component-lib/package-lock.json, component-lib/package.json
let's added to our dev dependencies.
=> babel-eslint is required for build and bundling, 

component-lib/src/molecules/PageHeader/PageHeader.jsx, component-lib/src/molecules/PageHeader/PageHeader.pcss
Makes the button/link for shopping cart look more similar to the login-button.
Also made the counter look more "Telia"-styled.
=> Add text "Handlekurv" to the shopping cart menu item and update styling for counter

component-lib/src/molecules/PageHeader/PageHeader.jsx, src/client/examples/molecules/PageHeader/[05]SecondTabSelected.js
Adds menuSelectedTabIndex prop to <PageHeader> so that you can, for example, make "Bedrift" the default menu tab selected on Bedrifts pages.
=> Add menuSelectedTabIndex to <PageHeader>

component-lib/src/molecules/PageHeader/PageHeader.jsx, component-lib/src/molecules/PageHeader/PageHeader.pcss, src/client/examples/molecules/PageHeader/[02]LoggedOut,3ItemsInCart.js, src/client/examples/molecules/PageHeader/[04]LoggedIn,1ItemInCart.js
The prop will accept a function, that is used to set the cart as open/closed.
Cart is currently not in the StyleGuide, because it is being redesigned. Will add it once design is done.
Right now it will open a cart implemented in Rapidshop.
=> PageHeader - Add onClick prop for cart button

component-lib/src/molecules/PageHeader/PageHeader.jsx, src/client/examples/molecules/PageHeader/[01]LoggedOut,NoItemsInCart.js, src/client/examples/molecules/PageHeader/[03]LoggedIn,NoItemsInCart.js, src/client/examples/molecules/PageMenu/[01]Default.js
Moved searchUrl prop out of PageMenu to PageHeader
=> Bugfix for PageMenu and PageHeader

component-lib/src/molecules/PageMenu/PageMenu.pcss
consider adding CSS animation with translate while opening and closing the hamburger menu
=> CSS animation for hamburger menu

component-lib/src/atoms/Button/Button.jsx, component-lib/src/atoms/Button/Button.pcss
=> Fixed such that disabled prop for button work properly

component-lib/src/molecules/TextBoxWithLabel/TextBoxWithLabel.jsx, src/client/examples/molecules/TextBoxWithLabel/[07]WithRef.js
=> Added forwarding of ref to input field for TextBoxWithLabel molecule

component-lib/src/molecules/Hero/Hero.jsx, component-lib/src/molecules/Hero/Hero.pcss
- Update version number before merge
=> Decreased height of Hero image

component-lib/src/atoms/Box/Box.jsx, component-lib/src/atoms/Box/Box.pcss, component-lib/src/molecules/Subscription/Subscription.pcss
* Added `black` for color option to `Box` and `Subscription`.
* Changed `dotted` to `dashed` for `Box` speech buble.
=> Adding black as color option to Box/Sub and changed dotted with dashed

component-lib/package.json, component-lib/src/atoms/Label/Label.pcss, package.json
Bjørn Even wanted this and got it...
=> Label styling

component-lib/src/molecules/RadioButtonList/RadioButtonList.jsx, component-lib/src/molecules/RadioButtonList/RadioButtonWithLabel.jsx
Hi, wanted to add this callback so the parent component can know what radio button is selected.
=> RadioButtonList onChange prop added

component-lib/package.json, component-lib/src/molecules/Menu/Menu.pcss, component-lib/src/molecules/Menu/MenuContent.pcss, component-lib/src/molecules/Menu/MobileMenu.pcss, package.json
=> Decreased z-index of new menu

component-lib/package.json, component-lib/src/molecules/Menu/MenuContent.pcss, package.json
This is not a good solution as it will break each time a new button type is added. Please help me think of a better way to make it more specific or if it is possible to change how we style the button component.
=> Updated styling of menu login button to fix bug after negative button was added

component-lib/src/molecules/CheckBoxWithLabel/CheckBoxWithLabel.jsx, component-lib/src/molecules/CheckBoxWithLabel/CheckBoxWithLabel.pcss, src/components/examples/molecules/CheckBoxWithLabel/Disabled.js
I've added a disabled state to CheckBoxWithLabel with some basic styling as it has been missing for quite some time.
I'm not very familiar with common conventions withing the styleguide but it should be ok.
=> Added disabled state for CheckBoxWithLabel component.

package-lock.json, package.json, src/components/App.js, src/components/pages/ComponentsAtomicPage.jsx, src/components/pages/ComponentsPage.jsx
Fixed the links to the component categories that did not work.
Added package so hash links works in the atomic structure
Remaining: Reset scroll position to top after transitions
=> Fixed linking with HashRouter

component-lib/package-lock.json, component-lib/src/molecules/Menu/MobileMenu.jsx, component-lib/src/molecules/Menu/MobileMenu.pcss, package-lock.json
=> moving privat bedrift top left corner

component-lib/package.json, component-lib/src/molecules/Menu/MenuContent.jsx
replace hardcoded **<a>** tag by configurable **LinkTemplate** prop for _Login_ and _Min Side_ links
=> Use LinkTemplate prop for Login and MinSide URL links

component-lib/src/atoms/QuantityPicker/QuantityButton.jsx, component-lib/src/atoms/QuantityPicker/QuantityPicker.jsx, component-lib/src/atoms/QuantityPicker/QuantityPicker.pcss, component-lib/src/atoms/QuantityPicker/index.js, component-lib/src/index.js, src/components/examples/atoms/QuantityPicker/Default.js
Add new atom: QuantityPicker. My first Styleguide component, so please tell me if something needs changes.
I couldn't get the documentation to work as seen above
=> Add QuantityPicker component

component-lib/package-lock.json, component-lib/package.json
Version 1.0.0 failed on Node 12 on OSX due to bluebirds promisifyAll function.
=> Upgrade @telia/svg-join

component-lib/src/molecules/ShoppingCart/ShoppingCartItem.jsx
isAnyCartItemsRemovable now makes all items removable regardless of the value of isRemovable
=> Fix isAnyCartItemsRemovable

.prettierignore, component-lib/.prettierignore, component-lib/src/molecules/Tooltip/Tooltip.d.ts, component-lib/src/molecules/Tooltip/Tooltip.jsx, src/components/examples/molecules/Tooltip/01-Default.js, src/components/examples/molecules/Tooltip/02-ShowInfo.js, src/components/examples/molecules/Tooltip/03-InContextOf-aLabel.js, src/components/examples/molecules/Tooltip/03-InContextOfLabel.js, src/components/examples/molecules/Tooltip/04-ComplexContent.js, src/components/examples/molecules/Tooltip/04-ShowInfoInContextOfLabel.js, src/css/index.pcss
Tooltip changes:
- Dynamic id generation to avoid elements with duplicate ids
- button type to avoid unexpected form submit 
- useState hook for showing expanded content
- support for replacing (i) for anything
- support for complex children content instead of only text
- support for extra className
- optional label element becomes a sibling of button instead or wrapping it
=> feature: Tooltip hook with expanded state

component-lib/src/molecules/ModalDialog/ModalDialog.pcss
=> border-radius: from % to rem

component-lib/src/atoms/Icon/Icon.pcss
Removed display:block from Icon css
=> Show Icon as inline element

component-lib/src/molecules/ShoppingCart/ShoppingCartTableFooter.pcss
Contrast was poor. Changing from white to black font color for better contrast.
=> Changed color on shopping cart footer row

component-lib/.storybook/preview.js, component-lib/src/stories/business/Contributing.stories.tsx, component-lib/src/stories/home/ColorPalette.stories.tsx, component-lib/src/stories/home/Contributing.stories.tsx, component-lib/src/stories/home/DownloadInstall.stories.tsx, component-lib/src/stories/home/Greetings.stories.tsx, component-lib/src/stories/home/Layout.stories.tsx, component-lib/src/stories/home/Typography.stories.tsx, component-lib/src/stories/home/Versions.stories.tsx
Put Greetings first, removed addon panel for a few different pages
=> Presentation order, adjustments in Storybook

component-lib/src/molecules/FunkyTabs/FunkyTab.jsx, component-lib/src/molecules/FunkyTabs/FunkyTabs.d.ts, component-lib/src/molecules/FunkyTabs/FunkyTabs.jsx, component-lib/src/molecules/FunkyTabs/FunkyTabs.pcss, component-lib/src/molecules/FunkyTabs/FunkyTabs.stories.tsx, component-lib/src/molecules/Subscription/Subscription.jsx, component-lib/src/molecules/Subscription/Subscription.pcss
* Add `noImages` to `FunkyTabs` component. Also remove padding/margin if no images.
* Correct line height for Subscription with extra data tags.
=> Tweaks to subscription and funkytabs

component-lib/src/atoms/ColorPicker/ColorPicker.d.ts, component-lib/src/atoms/ColorPicker/ColorPicker.jsx, component-lib/src/atoms/ColorPicker/ColorPicker.pcss, component-lib/src/atoms/ColorPicker/ColorPicker.stories.tsx, component-lib/src/atoms/ColorPicker/index.ts, component-lib/src/index.ts
=> Added ColorPicker component

component-lib/src/index.ts, component-lib/src/molecules/InfoCard/InfoCard.d.ts, component-lib/src/molecules/InfoCard/InfoCard.jsx, component-lib/src/molecules/InfoCard/InfoCard.pcss, component-lib/src/molecules/InfoCard/InfoCard.stories.tsx, component-lib/src/molecules/InfoCard/index.ts
=> Added InfoCard component

component-lib/src/business/Checkbox/Checkbox.tsx
Added inline-styling on checkbox
=> Added inline-styling on checkbox

README.md, src/components/pages/HomePage.jsx
+ At / add alert about migrating to storybook + link
+ improve docs
=> At / add alert about migrating to storybook + link

component-lib/src/business/Dropdown/Dropdown.pcss, component-lib/src/business/Dropdown/Dropdown.stories.tsx, component-lib/src/business/Dropdown/Dropdown.tsx, component-lib/src/business/Dropdown/DropdownItem.tsx, component-lib/src/business/Dropdown/DropdownMenu.tsx, component-lib/src/business/Dropdown/DropdownToggle.tsx, component-lib/src/business/Dropdown/context.ts, component-lib/src/business/Dropdown/index.ts, component-lib/src/business/Dropdown/useA11yDropdown.ts, component-lib/src/business/Dropdown/useAccessibleDropdown.ts, component-lib/src/business/index.tsx
- Add component for search/input field as toggle
- Add component for search/input field within the dropdown menu
- Keep focus in the input field when navigation through the dropdown items 
- Select dropdown item based on highlight index
=> Add support for search in business dropdown

component-lib/src/molecules/SubscriptionAccordion/SubscriptionAccordion.jsx, component-lib/src/molecules/SubscriptionAccordion/SubscriptionAccordion.pcss, component-lib/src/molecules/SubscriptionAccordion/SubscriptionAccordion.stories.tsx
* Primary button
* Remove last hr
* Added one more example
=> SubscriptionAccordion

component-lib/src/molecules/SubscriptionAccordion/SubscriptionAccordion.d.ts, component-lib/src/molecules/SubscriptionAccordion/SubscriptionAccordion.jsx, component-lib/src/molecules/SubscriptionAccordion/SubscriptionAccordion.stories.tsx
Remove logic to render button.
This should be handled by consumer instead through children prop.
=> SubscriptionAccordion changes

ci/tasks/build-website/task.yml
This is the first step -- everything else is still in place.
=> Publish Storybook to root URL, stop using the web site

src/business/Toggle/Toggle.pcss, src/business/Toggle/Toggle.tsx
Venter på løsning for tabbing/focus
=> Update business-toggle component

src/business/List/List.pcss
Jeg ønsker ikke padding på listene jeg skal bruke, så da tenker jeg man heller kan wrappe det inn i en div med padding hvis man trenger det?
=> Remove padding from list

src/atoms/RadioButton/RadioButton.jsx, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.d.ts, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.jsx, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.pcss, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.stories.tsx, src/molecules/SubscriptionLinesAccordion/index.ts
Inverted version looks a bit weird when focused/hovered, need to talk to UX-designer about that.
Also had to add onMouseEnter and onMouseLeave in the radio button component cause when clicking the radio button, the accordion also expanded.
=> Add SubscriptionLinesAccordion component

src/business/TextField/TextField.pcss, src/business/TextField/TextField.stories.tsx, src/business/TextField/TextField.tsx, src/business/TextField/index.ts, src/business/TextField/useFocus.ts, src/business/TextField/useTextField.ts
Figma sketches: https://www.figma.com/file/DY2nAi4QVg4DZWQSGP1A0n/Text-field?node-id=2%3A2
**Should replace existing text field in the not so distant future.** 
TODO: update the Dropdown with search, and add styles and documentation for "quick search"  https://www.figma.com/file/EBjS8URGPnFXU0SQsVL9la/Quick-search?node-id=2%3A2
=> Add business textfield

src/molecules/Avatar/Avatar.pcss, src/molecules/Avatar/Avatar.stories.tsx, src/molecules/Avatar/Avatar.tsx
Som avtalt med Jonathan. Ikke dokumentert i Fima enda
=> Support all avatar colors

src/business/Button/Button.stories.tsx, src/business/Button/Button.tsx
Jeg generaliserte Button-storeis, men så kom jeg til å tenke på at koden i docs ikke blir like god da..  Hva synes du?
=> Add taget props to button

src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.d.ts, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.jsx, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.pcss, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.stories.tsx
Change to styleguide integrated Helvetica fonts
=> Fix fonts on <SubscriptionLinesAccordion>

src/business/Checkbox/Checkbox.pcss, src/business/Table/Table.pcss, src/business/Table/Table.stories.tsx, src/business/Table/Table.tsx, src/business/Table/useTableState.ts
- Handle selectable and clickable rows 
- support fixed width 
- support skeleton loading 
- support connected rows
=> Adjustments to business table

assets/allicons/AllIcons.d.ts
Add missing Declare for AllIcons.
=> Declare AllIcons

src/molecules/ModalDialog/ModalDialog.pcss
=> Change z-index of ModalDialog

src/molecules/ShoppingCart/ShoppingCartItem.jsx, src/molecules/ShoppingCart/ShoppingCartTableFooter.jsx
The latter did not work with google optimize
=> Use classes instead of id's

src/atoms/StepIndicator/StepIndicator.jsx
=> Remove void 0

src/index.ts, src/molecules/Incrementer/Incrementer.pcss, src/molecules/Incrementer/Incrementer.stories.tsx, src/molecules/Incrementer/Incrementer.tsx, src/molecules/Incrementer/index.ts
https://www.figma.com/file/w5gRepPs7LBnW3QIx6Lly7/Incrementer?node-id=2%3A2
=> Add incrementer

src/organisms/SlidingShoppingCart/SlidingShoppingCart.pcss
Needed to support quantity picker in the cart on medium sized screens
=> Adjust width of sliding shopping cart

src/business/StepFlow/StepFlow.pcss, src/business/StepFlow/StepFlow.stories.tsx, src/business/StepFlow/StepFlow.tsx
Any ideas on naming for that prop? 😄 
I also refactored the stories a bit and updated the background color according to the sketches.
=> support additional content in step flow

src/business/Button/Button.pcss
I noticed that the buttons got different heights depending on how/where it was used, so i set the height to fixed according to the sketches
=> Fix  height of business buttons

src/molecules/Dropdown/Dropdown.pcss, src/molecules/Dropdown/Dropdown.stories.tsx, src/molecules/Dropdown/DropdownMenu.tsx
combinations of top/bottom left/right
=> support more positions for the dropdown menu

src/molecules/Dropdown/Dropdown.stories.tsx, src/molecules/Dropdown/DropdownItem.tsx, src/molecules/Dropdown/useAccessibleDropdown.ts
- and fix click highlighted item on enter
=> Fix focus in dropdown search item

src/atoms/Badge/Badge.pcss, src/atoms/Badge/Badge.stories.tsx, src/atoms/Badge/Badge.tsx, src/atoms/Badge/index.ts, src/index.ts
Not sure if we should support positioning the badge relative to its child (eg. in the top right corner of the child, like a notification). I've looked into how other libs do it, and it seems to be a common practice. I can imagine it being useful for notifications etc. What do you think, should we support it? Might as well? 
Ref: https://material-ui.com/components/badges/#dot-badge
=> add badge component

src/atoms/ColorPicker/ColorPicker.pcss, src/molecules/BigImageDialog/BigImageDialog.pcss
Only z-index is changed for BigImageDialog. The rest is prettier formatting 👍
=> Adjust height of ColorPicker and z-index of BigImageDialog

src/molecules/ShoppingCart/ShoppingCartItem.pcss
Only changed 'Helvetica Neue Regular' to 'Helvetica Neue'. Rest is prettier fixing formatting.
=> Change ShoppingCart delete font

src/business/StepFlow/StepFlow.pcss, src/business/StepFlow/StepFlow.stories.tsx, src/business/StepFlow/StepFlow.tsx, src/utils/useBreakpoint.ts
Make additional content slightly larger and change the breaking point to xxl.
Change the menu breaking point to lg and add ellipsis if the menu item overflows.
=> change additional content size

src/colors.pcss, src/stories/lib/colorsJSON.ts, src/utils/colors.ts
Figma: https://www.figma.com/file/fmkYKbB3jlIHN4EfeyL0fx/Colours?node-id=19%3A84
On request from Bjørn Even
=> Adding more colors

src/index.ts, src/molecules/SubscriptionAccordion/SubscriptionAccordionSimple.pcss, src/molecules/SubscriptionAccordion/SubscriptionAccordionSimple.stories.tsx, src/molecules/SubscriptionAccordion/SubscriptionAccordionSimple.tsx
Has only a few fields, with full width title
=> Added simple version of SubscriptionAccordion

src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.jsx, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.pcss, src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.stories.tsx
=> Right align part of SubscriptionLinesAccordion

src/molecules/Alert/Alert.pcss
=> align icons center

VERSIONS.md, src/molecules/BreadCrumbs/BreadCrumbs.d.ts, src/molecules/BreadCrumbs/BreadCrumbs.jsx, src/molecules/BreadCrumbs/BreadCrumbs.stories.tsx
Fix bug when crumbs prop is undefined and null. Made crumb[] nullable.
=> Fix bug when crumbs array is undefined

src/molecules/HardwareProductBox/HardwareProductBox.pcss, src/molecules/HardwareProductBox/HardwareProductBox.stories.tsx, src/molecules/HardwareProductBox/HardwareProductBox.tsx
Example views:
The `highlight` feature has very narrow space, on both desktop and phone, so it could potentially overflow or look weird if the texts are medium to long.
=> HardwareProductBox small device

src/business/Card/Card.pcss, src/business/Card/Card.stories.tsx, src/business/Card/CardOption.tsx
- and improve layout for cards without header
=> Support disabled card options 

src/molecules/HardwareProductBox/HardwareProductBox.pcss, src/molecules/HardwareProductBox/HardwareProductBox.stories.tsx
=> css tweaks to better match design

src/molecules/Breadcrumbs/Breadcrumbs.jsx, src/molecules/Breadcrumbs/Breadcrumbs.pcss, src/molecules/Breadcrumbs/Breadcrumbs.stories.tsx
=> replaced left arrow with right arrow

src/molecules/HardwareProductBox/HardwareProductBox.pcss, src/molecules/HardwareProductBox/HardwareProductBox.stories.tsx
1.  Removed scaling animation
2.  Rounded corners
3.  Thicker animated purple line (1px -> 2px)
4.  Permanent shadow on productbox
=> fixed blurry elements when scaling box

src/molecules/PhoneNumberField/PhoneNumberField.tsx, src/molecules/TextField/TextField.tsx
=> Phone input field props

src/molecules/ShoppingCart/ShoppingCart.stories.tsx, src/molecules/ShoppingCart/ShoppingCartItem.jsx, src/molecules/ShoppingCart/ShoppingCartItem.pcss
With states for active and draft
=> Added a status field for cart item

VERSIONS.md, src/atoms/Checkbox/Checkbox.pcss, src/atoms/RadioButton/RadioButton.pcss, src/business/Button/Button.pcss, src/business/Card/Card.pcss, src/business/List/List.pcss, src/business/Table/Table.pcss, src/business/Tabs/Tabs.pcss, src/business/Tooltip/Tooltip.pcss, src/colors.pcss, src/molecules/BigImageDialog/BigImageDialog.pcss, src/molecules/Breadcrumbs/Breadcrumbs.pcss, src/molecules/Chip/Chip.pcss, src/molecules/DatePicker/DataPicker.pcss, src/molecules/Dropdown/Dropdown.pcss, src/molecules/FieldInstructions/FieldInstructions.pcss, src/molecules/Incrementer/Incrementer.pcss, src/molecules/InfoCard/InfoCard.pcss, src/molecules/Lozenge/Lozenge.pcss, src/molecules/Lozenge/Lozenge.stories.tsx, src/molecules/Lozenge/Lozenge.tsx, src/molecules/Menu/MenuDropdown.pcss, src/molecules/MobileNavBar/MobileNavBar.pcss, src/molecules/PhoneNumberField/PhoneNumberField.pcss, src/molecules/QuickSearch/QuickSearch.pcss, src/molecules/RadioButtonGroup/RadioButtonGroup.pcss, src/molecules/SideMenu/SideMenu.pcss, src/molecules/TextField/TextField.pcss
Updating the colour palette with new VOCA-colors. 
No breaking changes, but there will be visual changes for those using grey100.
VOCA's grey100  = our grey200
Recommend changing grey200 --> grey100  when updating the styleguide package with this change.
=> Update to VOCA colors

src/business/Button/Button.stories.tsx, src/business/Button/Button.tsx
provides accessible label when no text is passed to button
=> add aria label prop

src/molecules/HardwareProductBox/HardwareProductBox.pcss, src/molecules/HardwareProductBox/HardwareProductBox.stories.tsx
And use new color schemes for banner in stories
=> Small css change for border

src/molecules/Tabs/Tabs.d.ts, src/molecules/Tabs/Tabs.jsx, src/molecules/Tabs/Tabs.pcss, src/molecules/Tabs/Tabs.stories.tsx
=> Added a full border version of Tabs component

src/molecules/InfoCard/InfoCard.jsx, src/molecules/InfoCard/InfoCard.pcss
=> icon change

src/business/Table/Table.pcss
Allow hover styles to be customised
=> hover on td instead of tr

ci/tasks/build-website/task.yml, ci/tasks/lint-test/task.yml, ci/tasks/update-and-publish-npm/task.yml
Issue might be related to garbage collection => trying to bump node version to get rid of image tags
=> Try to bump node to fix issue in pipeline

src/business/PageLayout/PageLayout.pcss, src/business/StepFlow/StepFlow.pcss, src/business/StepFlow/StepFlow.stories.tsx, src/business/StepFlow/StepFlow.tsx, src/business/StepFlow/StepFlowHeader.tsx
Added support for having navbar instead of cancel btn  (migration flow)
=> Make cancel btn optional and support navbar in Stepflow

src/business/PageLayout/PageLayout.pcss
=> Fix height for page layout to make bgr color stretch

VERSIONS.md, src/molecules/Modal/Modal.pcss, src/molecules/Modal/Modal.stories.tsx, src/molecules/Modal/Modal.tsx
* Blocks background scrolling
* Blocks tabbing outside modal on first tab
* Return focus to original trigger or a specified html element
* add role of dialog
* add aria-labelledby as a required prop in Modal
=> Accessibility update

src/organisms/ShoppingCartAccordion/ShoppingCartAccordion.jsx, src/organisms/ShoppingCartAccordion/ShoppingCartAccordion.pcss, src/organisms/ShoppingCartAccordion/ShoppingCartAccordion.stories.tsx
Will only show accordion if it is expanded
=> Added flag shouldShowOnlyOnExpanded

package-lock.json, package.json, src/molecules/ShoppingCartUpdated/ShoppingCart.pcss, src/molecules/ShoppingCartUpdated/ShoppingCart.stories.tsx, src/molecules/ShoppingCartUpdated/ShoppingCart.tsx, src/molecules/ShoppingCartUpdated/ShoppingCartPaymentSection.tsx
=> Payment section for new shopping cart

src/molecules/Menu/MenuCart.pcss, src/organisms/SlidingShoppingCartUpdated/SlidingShoppingCartUpdated.tsx, src/organisms/SlidingShoppingCartUpdated/SlidingShopppingCartUpdated.pcss
=> Trap focus in sliding shopping cart if open

src/molecules/ShoppingCartV2/ShoppingCart.pcss, src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartPaymentSection.tsx, src/molecules/ShoppingCartV2/ShoppingCartV2.tsx
=> added disclaimer

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartPaymentSection.tsx
=> Added first invoice price row

src/molecules/ShoppingCartV2/ShoppingCart.pcss, src/molecules/ShoppingCartV2/ShoppingCartPaymentSection.tsx, src/molecules/ShoppingCartV2/ShoppingCartV2.tsx, src/organisms/SlidingShoppingCartV2/SlidingShoppingCartV2.stories.tsx
Also add small padding on bottom
=> Make disclaimer bg follow that of parent of SC

src/atoms/QuantityPicker/QuantityPicker.d.ts, src/atoms/QuantityPicker/QuantityPicker.jsx, src/atoms/QuantityPicker/QuantityPicker.pcss, src/atoms/QuantityPicker/QuantityPicker.stories.tsx
=> Added compact version of QuantityPicker

src/molecules/SideMenu/SideMenuItem.tsx
=> prevente default on tablet

.github/workflows/publish-to-npm.yml
Reverts TeliaSoneraNorge/styleguide#1195
=> Revert "Feature/try to use setup node v3"

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx, src/molecules/ShoppingCartV2/ShoppingCartItemSection.tsx, src/molecules/ShoppingCartV2/ShoppingCartPaymentSection.tsx, src/molecules/ShoppingCartV2/ShoppingCartV2.tsx
Show "Betalt"
Dont show quantity picker buttons
Screen:
=> If hasPaid, make some changes to cart shown

src/molecules/SubscriptionAccordion/SubscriptionAccordion.d.ts, src/molecules/SubscriptionAccordion/SubscriptionAccordion.jsx, src/molecules/SubscriptionAccordion/SubscriptionAccordion.pcss, src/molecules/SubscriptionAccordion/SubscriptionAccordion.stories.tsx
=> Added ribbon for SubscriptionAccordion

src/business/Button/Button.tsx, src/business/Table/Table.tsx
Added optional refs so that we can manage focus between our list/table and details card view
=> add optional ref to TableBodyRow 

src/molecules/AccordionFlexible/AccordionFlexible.d.ts
My build using the latest version of this package broke on these two errors.
=> Fix typescript errors

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx, src/molecules/ShoppingCartV2/types.ts, src/molecules/SpeechBubble/SpeechBubble.pcss, src/molecules/SpeechBubble/SpeechBubble.stories.tsx, src/molecules/SpeechBubble/SpeechBubble.tsx
https://user-images.githubusercontent.com/11172530/195306445-04c024ef-8c7d-467d-b0b3-2ae467a53d5a.mov
=> Display handset discount in ShoppingCart

package-lock.json, package.json, src/index.ts, src/molecules/SpeechBubble/SpeechBubble.pcss, src/molecules/SpeechBubble/SpeechBubble.stories.tsx, src/molecules/SpeechBubble/SpeechBubble.tsx, src/molecules/SpeechBubble/index.ts
https://user-images.githubusercontent.com/11172530/195304940-d02c572e-f717-4944-80b8-e8059329dd1a.mov
=> Add SpeechBubble component

src/molecules/StepIndicatorPaging/Data/StepDataChildrenAsHtmlWithUrls.tsx, src/molecules/StepIndicatorPaging/Models/Props.tsx, src/molecules/StepIndicatorPaging/StepIndicatorPaging.stories.tsx, src/molecules/StepIndicatorPaging/StepIndicatorPaging.tsx
basic logic to find the initial step based on current path only (ignores query strings for now)
=> New prop - autoSetStepFromUrl

src/atoms/Badge/Badge.tsx, src/atoms/SummaryTable/SummaryTable.pcss, src/atoms/SummaryTable/SummaryTable.stories.tsx, src/atoms/SummaryTable/SummaryTable.tsx
- added grey background option
- added title option
- added badge option
- added 'description option' which shows below "price" per item
- added multiple stories/variations
=> SummaryTable

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartItem.pcss, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx, src/molecules/ShoppingCartV2/types.ts
=> NOCT-25226: Add Lozenge with discount text when `cartItem.discount.types[0]` exists.

src/molecules/ShoppingCartV2/ShoppingCartItem.tsx
=> NOCT-25226: Place original price on top, and discounted price on the bottom

src/molecules/BundleDealBox/BundleDealBox.pcss
|---|---|
| ![Screenshot 2023-01-10 at 13 33 19](https://user-images.githubusercontent.com/11172530/211553147-f2cf9e9c-317b-45d9-afac-e02c1eaa52f9.png)  | ![Screenshot 2023-01-10 at 13 33 29](https://user-images.githubusercontent.com/11172530/211553157-2a6c786f-280e-49e5-93e8-68fc610530fb.png)  |
=> BundleDealBox: Center align flashText

src/molecules/HardwareProductBox/HardwareProductBox.pcss, src/molecules/HardwareProductBox/HardwareProductBox.stories.tsx
|---|---|
|  ![image](https://user-images.githubusercontent.com/11172530/228473452-a1c3f733-2858-44c8-856a-82a16bd16c98.png) | ![image](https://user-images.githubusercontent.com/11172530/228473379-cc3240bc-3016-437f-8ff9-eacc4dfa362b.png)  |
=> Text on HardwareProductBox should not be uppercase

src/molecules/AccordionFlexible/AccordionFlexible.pcss, src/molecules/Chip/Chip.pcss, src/molecules/Modal/Modal.pcss
=> changing end, start to flex-end, flex-start to remove warnings

src/molecules/Alert/Alert.d.ts, src/molecules/Alert/Alert.jsx, src/molecules/Alert/Alert.pcss, src/molecules/Alert/Alert.stories.tsx
Smaller icon by default
Align top left icon and text
Screen:
=> Alert changes

src/molecules/Menu/Menu.d.ts, src/molecules/Menu/Menu.jsx, src/molecules/Menu/Menu.stories.tsx, src/molecules/Menu/MenuContent.jsx, src/molecules/Menu/MobileMenu/MobileMenu.jsx, src/molecules/Menu/MobileMenu/MobileMenuHeader.jsx
added buttonValues prop in Menu component to override: `logg inn`, `min side`, `Forside`, `Lukk` button values
=> feat: added buttonValues prop in Menu component

src/molecules/SideMenu/SideMenuItemGroup.tsx
Added data-tracking-id to SideMenuItemGroup component for testing purposes
=> Add missing DTID to SideMenuItemGroup component

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx
=> added footer for unexpanded accordion

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartFamilyDiscountInfo.pcss, src/molecules/ShoppingCartV2/ShoppingCartFamilyDiscountInfo.tsx, src/molecules/ShoppingCartV2/ShoppingCartV2.tsx
https://trello.com/c/tJMkKCjQ/2925-show-du-kan-f%C3%A5-rabatt-in-cart
=> ShoppingCart: Add family discount info

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx
|---|---|
|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/328373c5-2b56-4ebe-9420-fa370b9fe0d8)|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/d6332aa0-21b6-4b2e-a853-075792f1b6dd)|
=> Shopping cart discount: Change Lozenge color

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss
https://trello.com/c/F1h1S5R3/2979-athena-small-fixes-batch-2
=> CSS tweaks to compact accordion

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx
=> add hover effect and change border radius

src/molecules/ShoppingCartV2/ShoppingCartFamilyDiscountInfo.pcss, src/molecules/ShoppingCartV2/ShoppingCartFamilyDiscountInfo.tsx
=> ShoppingCartFamilyDiscountInfo: Text change

src/atoms/Button/Button.pcss, src/atoms/Button/Button.stories.tsx, src/atoms/Button/Button.tsx, src/colors.pcss
=> purple voca button

src/atoms/Button/Button.pcss, src/atoms/Button/Button.stories.tsx, src/atoms/Button/Button.tsx
=> add voca purple inverted button

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss
https://trello.com/c/NOzhe8Nb/3137-subscriptioncompact-margin-shadow-border
Some tiny changes our designer pinpointed.
|---|---|
|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/65a40a3d-c58e-44ec-8d46-b47fdf012519)|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/3902fb86-7024-4fdd-bb26-94e0e4cdad44)|
=> SubscriptionCompactAccordion: Border and box-shadow changes

src/atoms/SmallBoxList/SmallBoxList.pcss, src/atoms/SmallBoxList/SmallBoxList.stories.tsx, src/atoms/SmallBoxList/SmallBoxList.tsx
=> Added purple variant to small box list

src/atoms/RadioButton/RadioButton.pcss, src/colors.pcss
=> add new color

src/molecules/SpeechBubbleTabs/SpeechBubbleTabs.pcss, src/molecules/SpeechBubbleTabs/SpeechBubbleTabs.stories.tsx, src/molecules/SpeechBubbleTabs/SpeechBubbleTabs.tsx
Needed for this: https://trello.com/c/zJK035rJ/3121-lik-st%C3%B8rrelse-p%C3%A5-tabs-i-fwa-flyt-som-p%C3%A5-mobil-listesider
|---|---|
|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/41b84256-4746-4d9c-b016-6e7ca9adf933)|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/d2856d56-e79d-4473-99ee-59114e413d75)|
=> SpeechBubbleTabs: Add option to hide triangle, adjust padding slightly

.storybook/main.js, src/atoms/Toggle/Toggle.stories.tsx, src/atoms/Toggle/Toggle.tsx, src/business/MainMenu/MainMenu.stories.tsx, src/business/MainMenu/MainMenu.tsx, src/molecules/Paging/TablePagination.tsx
We have a local storybook in our project, https://github.com/TeliaSoneraNorge/telia-no-min-side
I'd like to compose this storybook with our local one, like this:
https://github.com/TeliaSoneraNorge/styleguide/assets/6454520/eac03c57-4924-437e-8aa3-dd6fe652246e
More: https://storybook.js.org/docs/react/sharing/storybook-composition
Complementary PR in our project: https://github.com/TeliaSoneraNorge/telia-no-min-side/pull/1353
=> enable storybook composition

src/atoms/Button/Button.pcss, src/atoms/Button/Button.stories.tsx, src/atoms/Button/Button.tsx
=> Add extra small variant of button

src/molecules/BigImageDialog/BigImageDialog.d.ts, src/molecules/BigImageDialog/BigImageDialog.jsx, src/molecules/BigImageDialog/BigImageDialog.pcss, src/molecules/BigImageDialog/BigImageDialog.stories.tsx
Part of https://trello.com/c/JxSuUima/3218-compatible-accessories-style-fixes
Figma: https://www.figma.com/file/5I208zBjEnbXYXJL8RDqCz/HW-kj%C3%B8psl%C3%B8p?node-id=765%3A3816&mode=dev
|---|---|
|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/e086f877-519a-488d-b5bc-db9800dc9129)|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/8e3b56f4-2fa7-4db7-baf1-5e0f1207b527)|
=> BigImageDialog style changes

src/atoms/ProgressBar/ProgressBar.pcss, src/atoms/ProgressBar/ProgressBar.tsx, src/global.pcss, src/molecules/ShoppingCartV2/ShoppingCart.pcss, src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartPaymentSection.tsx, src/molecules/ShoppingCartV2/types.ts
=> Added progress bar option to delivery in cart

src/molecules/Menu/MenuCart.pcss
https://trello.com/c/sqik1ZRa
Shall be purple instad of green
=> Change item-count colour to purple

src/organisms/SlidingShoppingCartV2/SlidingShoppingCartV2.stories.tsx, src/organisms/SlidingShoppingCartV2/SlidingShoppingCartV2.tsx, src/organisms/SlidingShoppingCartV2/SlidingShopppingCartV2.pcss
=> show upfront and monthly

src/molecules/BundleDealBox/BundleDealBox.pcss, src/molecules/BundleDealBox/BundleDealBox.tsx
[screen-capture (3).webm](https://github.com/TeliaSoneraNorge/styleguide/assets/25934547/44a48694-6002-48fc-b388-9401c0dc6353)
=> clickable bundledealbox

src/organisms/SlidingShoppingCartV2/SlidingShoppingCartV2.tsx, src/organisms/SlidingShoppingCartV2/SlidingShopppingCartV2.pcss
Before:
After:
https://trello.com/c/1IFXrKDA
=> slidingShoppingCart: Change text and fix border styling

src/molecules/Lozenge/Lozenge.pcss, src/molecules/Lozenge/Lozenge.stories.tsx, src/molecules/Lozenge/Lozenge.tsx
=> align styling with purpur

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx, src/molecules/ShoppingCartV2/types.ts
=> Allow multiple subtitles on cartItem

src/index.ts, src/molecules/ServiceCard/ServiceCard.pcss, src/molecules/ServiceCard/ServiceCard.stories.tsx, src/molecules/ServiceCard/ServiceCard.tsx
=> add servicecard component

src/atoms/ColorPicker/ColorPicker.pcss, src/atoms/ColorPicker/ColorPicker.stories.tsx, src/atoms/ColorPicker/ColorPicker.tsx
=> Add s, m and l sizes to ColorPicker

src/molecules/ShoppingCartV2/ShoppingCartItem.tsx
https://trello.com/c/dDKzbfb7/3887-styleguide-shoppingcartitem-need-span
=> Need span around text to work with Google Translate.

src/atoms/Button/Button.tsx
https://trello.com/c/0sLn92Ta/3886-styleguide-button-need-span
=> Button need span around text to work with Google Translate.

src/atoms/SmallBoxList/SmallBoxList.pcss, src/atoms/SmallBoxList/SmallBoxList.stories.tsx, src/atoms/SmallBoxList/SmallBoxList.tsx
=> Add link option to SmallListBox

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx
Changes to
- Price layout
- Removed unused CSS
Screens
And used in webshop context
=> Changes to SubscriptionCompactAccordion

src/molecules/ShoppingCartV2/ShoppingCartFamilyDiscountInfo.tsx
Old:
---
New:
https://trello.com/c/3e5noTCu
=> Update text on cart infobox about family discount

src/molecules/ShoppingCartV2/ShoppingCart.pcss, src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartDisclaimerSection.pcss, src/molecules/ShoppingCartV2/ShoppingCartDisclaimerSection.tsx, src/molecules/ShoppingCartV2/ShoppingCartV2.tsx, src/molecules/ShoppingCartV2/types.ts
https://trello.com/c/ZFjmhK9X/3976-show-disclaimer-for-all-bundles-with-commitment
Collapsed:
Expanded:
=> ShoppingCart: Support multiple disclaimers in an accordion

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartDisclaimerSection.pcss, src/molecules/ShoppingCartV2/ShoppingCartDisclaimerSection.tsx, src/molecules/ShoppingCartV2/types.ts
=> ShoppingCartDisclaimerSection: Support multiple descriptions

src/molecules/HardwareProductBox/HardwareProductBox.pcss
https://github.com/user-attachments/assets/51964478-4335-4c4a-a536-512ea6643af1
=> Add 'textwrap: pretty' to product title in product box

src/molecules/BundleDealBox/BundleDealBox.pcss, src/molecules/BundleDealBox/BundleDealBox.stories.tsx
=> Remove height requirement

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx
https://trello.com/c/mRIxA8Gi/4620-add-family-discount-banner-to-subscriptions-card-available-for-discount
Desktop:
Mobile:
=> SubscriptionCompactAccordion: Add footer ribbon

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartFamilyDiscountInfo.tsx, src/molecules/ShoppingCartV2/ShoppingCartV2.tsx
https://trello.com/c/9oLX4zmD/4451-display-potential-discount-info-also-for-hw-orders
=> show name and link

src/molecules/ShoppingCartV2/ShoppingCart.pcss, src/molecules/ShoppingCartV2/ShoppingCartItem.pcss, src/molecules/ShoppingCartV2/ShoppingCartItemSection.tsx
https://trello.com/c/xvs31yAY/4913-design-uplift-in-cart
Screen:
=> Style changes to shopping cart item

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx, src/molecules/ShoppingCartV2/ShoppingCartItem.pcss, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx, src/molecules/ShoppingCartV2/types.ts
https://trello.com/c/Q1CaZ8XE/4911-as-a-customer-i-would-like-to-see-that-my-discount-code-is-activated-calculated
|---|---|
|![image](https://github.com/user-attachments/assets/8fb6b218-cee4-4fe5-b76d-4273c0a4d16c)|![image](https://github.com/user-attachments/assets/f26ed1ed-7a2a-4e88-a95f-1c66f8f6ad2e)|
=> Support displaying unique discount codes in cart

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx
https://trello.com/c/2waKAcJg/5207-add-support-for-ribbon-placement-for-subscriptioncards
[screen-capture (7).webm](https://github.com/user-attachments/assets/a46ee788-f2b4-4e30-8c18-44f2550db660)
=> support left or right ribbon placement

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx, src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx
Support sending in a discountinfo component to subscription:
=> support discountinfo

src/molecules/ShoppingCartV2/ShoppingCartItem.pcss, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx
https://trello.com/c/t8I5GnH2/5317-price-view-changes-to-cart
=> add disclaimer for discounted price in cart

src/molecules/ShoppingCartV2/ShoppingCartItem.pcss, src/molecules/ShoppingCartV2/ShoppingCartItem.tsx
https://trello.com/c/nsmUiEmw/4987-antallvelger-i-handlekurv-oppf%C3%B8rer-seg-rart-p%C3%A5-mobilversjon
Before  | After
------------- | -------------
=> Fix quantity icon for iphone

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss
=> Make subscription card heading left aligned

src/business/Table/Table.pcss, src/business/Table/Table.stories.tsx, src/business/Table/Table.tsx
Added new props:
- emptyTableTitle - Title of the state
- emptyTableDescription - Description of the state
- emptyTableButtonLabel - Label of the button
- emptyTableButtonOnClick - onClick func
=> refactor(Table): Added new props to empty table state
