TeliaSoneraNorge/styleguide

src/client/pages/BlogSamplePage1.jsx
src/client/pages/InformationArticleSample1.jsx
src/client/pages/InformationArticleSample3.jsx
src/components/atoms/FullWidthImage/FullWidthImage.html
src/components/atoms/FullWidthImage/FullWidthImage.md
src/components/atoms/FullWidthImage/FullWidthImage.pcss
src/components/atoms/FullWidthImage/FullWidthImage.with-mask.html
src/components/atoms/FullWidthImage/FullWidthImage.with-overlapping-content.html
src/components/global.pcss
src/unoptimized-icons/full-screen-image-mask.svg

Take a look at the "Albatross-skisser" board in inVision. Under the title "QA accordion + buet bilde ++" you can find an overview of the behavior the designers wanted the FullWidthImage to have according to responsivity. This is what these changes contains.  Also added a new mask that isn't as curvy as the last one. Try it and see if you think it seems fluid.

Changed FullWidthImage according to QA from designer

---

src/components/colors.pcss
src/components/molecules/Alert/Alert.jsx
src/components/molecules/Alert/Alert.jsx.Examples.json
src/components/molecules/Alert/Alert.pcss

Info type was added because it was used in current "flash messages" in RapidShop.
**NB! Also added role="alert" to all Alerts.**
This enables assistive technology to present the alert to the user when it is displayed on-screen.

Alert: Added type "info" and made small a11y improvement

---

src/client/pages/FormsSamplePage.jsx
src/components/atoms/Label/Label.jsx
src/components/atoms/Label/Label.jsx.Examples.json
src/components/atoms/Label/Label.pcss
src/components/colors.pcss
src/components/molecules/CheckBoxWithLabel/CheckBoxWithLabel.jsx
src/components/molecules/DropDownListWithLabel/DropDownListWithLabel.jsx
src/components/molecules/DropDownListWithLabel/DropDownListWithLabel.jsx.Examples.json
src/components/molecules/DropDownListWithLabel/DropDownListWithLabel.pcss
src/components/molecules/RadioButtonList/RadioButtonWithLabel.jsx
src/components/molecules/TextBoxWithLabel/TextBoxWithLabel.jsx
src/components/molecules/TextBoxWithLabel/TextBoxWithLabel.jsx.Examples.json
src/components/molecules/TextBoxWithLabel/TextBoxWithLabel.pcss
src/components/organisms/Form/Form.jsx
src/components/organisms/Form/Form.jsx.Examples.json

- `Label` doesn't have any "text-to-right" or anything else related to positioning. Only default, or gray text.
- `Label` can have `text` props or `children` passed in, to support simple labels or complex ones with child elements.
- `TextBoxWithLabel` has its `label` props renamed to `labelText`.
- `colors.pcss` matches the color grid we see in the UI.
- `DropDownListWithLabel` defaults to gray text on top.
- `TextBoxWithLabel` defaults to gray text on top.
- Labels, input borders and placeholder text have had their colors tweaked according to UX's wishes, because it was too light and hard to read before.

Label text and form color fixes

---

package.json
src/components/atoms/Caption/Caption.pcss
src/components/atoms/Heading/Heading.pcss
src/components/molecules/AccordionList/AccordionList.pcss
src/components/molecules/FocusBox/FocusBox.pcss
src/components/molecules/Image/Image.pcss
src/components/molecules/ListWithImage/ListWithImage.pcss

- Set margin-top in caption to 0 in case the css class is used on an element that has margin-top
- Removed margin-top on heading components; heading--level-2, 3 and 4
- Increased padding-right on accordion, so text doesn't touch the +/- icon
- Increased padding-top and bottom on FocusBox
- Image in image component is now 100% if bigger than container, if not it's rendered as it's exact size.
- Removing some of the margin on ListWithImage on mobile when the image doesn't show

Small fixes to some components

---

src/components/molecules/CheckBoxWithLabel/CheckBoxWithLabel.jsx.Examples.json
src/components/molecules/CheckBoxWithLabel/CheckBoxWithLabel.pcss
src/components/molecules/RadioButtonList/RadioButtonList.jsx
src/components/molecules/RadioButtonList/RadioButtonWithLabel.jsx
src/components/molecules/RadioButtonList/RadioButtonWithLabel.pcss

- Added focus styling on CheckBox (same as hover-styling)
- There already was a different kind of focus styling on RadioButtons, but I changed it to match CheckBox
- This is what the design in the "Rollover og Tab" sketch says, but it needs review from designer in case the sketch is no longer valid
- DESIGNER REVIEW OK

Same focus styling on checkbox and radio buttons

---

src/components/molecules/Hero/Hero.pcss

Fixed issue in Safari on iOS where .hero__heading was rendered with font-weight: bold

Bugfix for hero

---

component-lib/package.json
component-lib/rollup.build.js

Some project does not transpile their dependencies so they fail to load this library. Let's provide commonjs version, so the library would be easy to use.

Provide bundle with commonjs modules

---

VERSIONS.md
component-lib/src/molecules/PageMenu/PageMenu.jsx
package-lock.json
package.json
src/client/examples/molecules/PageMenu/[01]Default.js
src/client/examples/molecules/RichText/[01]Default.js

Allowed PageMenu to accept a string of html instead of a component in menuLinks.menuLink.contentAboveItems, so it plays nice with the new channelAPI/layout endpoint.
Also did some small updates to package-lock.json and fixed a console error for a RichText example

Make PageMenu accept html string for content above items

---

component-lib/src/molecules/FunkyTabs/FunkyTabs.jsx

As is, google will not index the different URL's using `FunkyTabs` component since it renders all content in DOM and use `display: none`. Google will then see all URL's alike, and only index the first one it encounters.
With this change, only the selected tabs content is rendered creating a DOM with only content for that tab, which hopefully will please the google god.

Rendering only one tab at a time for FunkyTabs

---

.eslintrc
component-lib/src/molecules/RadioButtonList/RadioButtonList.jsx
component-lib/src/molecules/RadioButtonList/RadioButtonWithLabel.jsx

- with `defaultChecked` it doesn't update the radio buttons when `selectedIndex` prop has changed
- it caused even more failures when `key={index}`
- so I added `react/no-array-index-key` lint rule which I couldn't set to "error" yet as the key=index is being used on loads of places

changed radio button defaultChecked prop to checked

---

component-lib/src/molecules/DropDownListWithLabel/DropDownListWithLabel.jsx

<DropDownListWithLabel />  is controlled component so it shouldn't have `defaultValue` prop but `value` (https://reactjs.org/docs/forms.html#controlled-components). With current `defaultValue` the select options won't update when `value` prop has changed

replaced defaultValue with value prop in <select /> element in <DropDownListWithLabel />

---

component-lib/src/atoms/SvgIcon/SvgIcon.jsx
component-lib/src/atoms/SvgIcon/SvgIcon.pcss
component-lib/src/colors.pcss
component-lib/src/constants.js
package.json
src/colors.json
src/components/common/Color.jsx
src/components/examples/atoms/SvgIcon/Default.js
src/components/pages/HomePage.jsx
src/css/index.pcss

=== COLOR CLEANUP ===
We had some outdated colors in the styleguide that have now been updated. 
Dont worry!
The old one still works ...
If you are using "grey" or "green", try to find some other alternatives in the styleguide color palette.
"purple" = "core-purple", please use "core-purple" instead, so there will be no misunderstandings.
There are 3 new colors added:
Additional colors means that they are not from the official Telia palette, but something Telia Norway
have created:
SvgIcon supports all the colors now :D
We still got some custom colors that we want to get rid of. 
Are anyone using one of theese colors?
--blue: #00CDFF;
--dark-grey-2: #726E6E;
--dark-purple-2: #642C96;
--emerald: #3ED35F;
--green: #32FF00;
--grey: #DEDEDE;
--grey-darker: #D8D8D8;
--lime: #CDFF32;
--teal: …

updateing colors and svgicon color support

---

component-lib/src/atoms/Box/Box.jsx
component-lib/src/atoms/Box/Box.pcss

Uppercase texts are read as abbreviations (letter-by-letter) by screen readers.
Also make sure button stretches out to bottom as well.

Add aria-label to have properly cased close button text on Box component

---

component-lib/package.json

Concourse appears to fail without:
https://concourse.common-services.telia.io/teams/channel-api/pipelines/styleguide/jobs/version-minor-and-publish-npm/builds/2

Fix: provide path to `tsc` in build script

---

VERSIONS.md
component-lib/src/atoms/QuantityPicker/QuantityPicker.jsx
component-lib/src/atoms/QuantityPicker/QuantityPicker.pcss
component-lib/src/atoms/Quote/Quote.pcss
component-lib/src/atoms/ToggleButton/ToggleButton.jsx

- Fix warning in ToggleButton component by setting defaultChecked to undefined if the prop is not explicitly set
- Fix warning in QuantityPicker which used to happen when erasing the input field
- Minor change to font-size of text in Quote component so it's more responsive. This is the sizes we use in RapidShop, so thought I would make the same change here.
- Add a name field to the input component of QuantityPicker for improved accessability.
Looks like the linter also automatically makes some formatting changes when pushing.

Fix warnings in QuantityPicker and ToggleButton, change font-size of Quote

---

component-lib/src/atoms/QuantityPicker/QuantityPicker.pcss

Fix that all browsers other than chrome displayed like this:

quantity picker browser support

---

component-lib/src/molecules/Accordion/Accordion.jsx

Add optional component at the bottom of the accordion component. In RapidShop we use it to add a color picker:

Add optional footer to accordion

---

component-lib/src/molecules/Alert/Alert.jsx

Add optional prop to hide icon in Alert. This is so we can hide the icon on mobile devices to give more space for the text.

Add optional prop to hide icon in Alert

---

component-lib/src/business/Table/Table.pcss
component-lib/src/business/Table/Table.stories.tsx
component-lib/src/business/Table/Table.tsx
component-lib/src/business/Table/index.ts
component-lib/src/business/Table/tableHooks.ts
component-lib/src/business/Table/useTableState.ts

Adds a custom hook for table state that can be used, also fixes paging to no longer be dependent on a page number, but only from/to props. So that, if you see from 11-20 and switch to 25 per page, you no longer jump to see from 26-50, but instead see 11-36.

Add hook and fix paging

---

component-lib/src/atoms/Button/Button.tsx
component-lib/src/atoms/Link/Link.tsx
component-lib/src/molecules/InfoBox/InfoBox.jsx
component-lib/src/molecules/LightAlert/LightAlert.jsx

The problem seemed to be the Button implementation imported the whole component-lib through `import ... from '../../index';`, causing a circular dependency when ModalDialog tried to import Button.kinds (before the Button definition itself had been completed).
I've updated the imports (including a couple others I found) to import specifically the components the source files need.

Updated imports to avoid circular dependencies in the component lib

---

ci/tasks/update-and-publish-npm/task.sh

This change automatically runs `npm run build:icons` when publishing to NPM.
I'm a bit torn on this -- a better solution would probably be to have a bot perform the change in the repo directly (so the generated files are automatically committed to the repo too).
But we do have a bit of autogeneration on publish already, so I guess it's a small improvement :man_shrugging:

Automatically build icons when publishing to NPM

---

component-lib/src/molecules/ShoppingCart/ShoppingCartItem.jsx

isNaN returns false for null which gives wrong result.
Also added 0 as correct fallback for discounts should their values be null

Replace !isNaN with _.isNumber

---

src/atoms/FullWidthTable/FullWidthTable.d.ts
src/atoms/FullWidthTable/FullWidthTable.jsx
src/atoms/FullWidthTable/FullWidthTable.stories.css
src/atoms/FullWidthTable/FullWidthTable.stories.pcss
src/atoms/FullWidthTable/FullWidthTable.stories.tsx

The className prop was not declared in the FullWidthTable components. This PR should fix it.
This changes might affect all sites. I hope it doesn't break anything. Please verify it works.
I also added some Storybook knobs for it (and the white footer, to reduce code)

declare className prop in all FullWidthTable components

---

src/molecules/BigImageDialog/BigImageDialog.d.ts
src/molecules/InfoCard/InfoCard.d.ts
src/molecules/SubscriptionAccordion/SubscriptionAccordion.d.ts
src/molecules/SubscriptionLinesAccordion/SubscriptionLinesAccordion.d.ts

TS1046: 'declare' modifier required for top level element
We get this error when using the Styleguide in using  "typescript": "^3.8.3".

Add missing export statements

---

src/molecules/SubscriptionAccordion/SubscriptionAccordion.jsx
src/molecules/SubscriptionAccordion/SubscriptionAccordion.pcss
src/molecules/SubscriptionAccordion/SubscriptionAccordion.stories.tsx

The discount overlapped a little the next subscription accordion. 
Adding a little more margin in this case to avoid that.

Add extra margin on small device when discount

---

src/molecules/DatePicker/DatePickerTimeInput.tsx
src/molecules/Dropdown/Dropdown.tsx
src/molecules/Dropdown/DropdownMenu.tsx

Har test den tab-index tingen i Dropdown-storyene også, og det funker fint. Den gjorde at man måtte tabbe to ganger for å komme ut av inputfeltet (fordi dropdown-menyen fikk fokus). Litt usikker på hvorfor det ikke har slått ut før 🤔

Fix time picker dropdown design across browsers

---

src/business/Button/Button.tsx

Burde vel egentlig stått "when button have an a tag" 😬  så ikke at det kunne misforstås før nå

Set type to undefined when  button have a tag

---

src/business/List/List.pcss
src/business/List/List.stories.tsx
src/business/List/ListCard.tsx
src/business/List/ListItem.tsx
src/business/List/ListItemSkeleton.tsx
src/business/List/utils.ts

- Remove shadow styling and replace it with outline (consistent with the Card component)
- Set inner div in ListItem to button if it is clickable
- Update border radius to 12px (will also be done for the Card component)
- Move expandedChildren to its own prop to keep using children as custom list items
- Remove hover effects when onClick is undefined

Update List with new style changes

---

src/molecules/Dropdown/Dropdown.pcss
src/molecules/Dropdown/Dropdown.stories.tsx
src/molecules/Dropdown/DropdownItem.tsx

This one will allow for a more spacious layout when using icons in a dropdown. Will use it as this graphics shows

Make possible additional paddding for the DropDownItem icon, if used

---

src/molecules/Dropdown/Dropdown.pcss
src/molecules/Dropdown/DropdownItem.tsx

This change makes it possible and/or cleaner to use the dropdown item with e.g. a leading icon without its styling to collide with what the styleguide dictates.

Use dedicated css classname instead of mixing with Icon component styling. Reduce cascading

---

src/molecules/TextField/TextField.pcss

It was decided at the ux meeting to use A0A0A0

Fix color for disabled label due to contrast

---

src/business/Button/Button.pcss
src/business/Button/Button.stories.tsx
src/business/Button/Button.tsx

Jobber med å få menyen til å slide over portalen på små skjermer. Da fant jeg ut at når man setter på opacity på bakgrunnen fungerer ikke dette på knappene, fordi de hadde relative på seg 😅  Måtte derfor refaktorere litt

Avoid using relative and translate to support overlay

---

src/molecules/ModalDialog/ModalDialog.d.ts
src/molecules/ModalDialog/ModalDialog.jsx

Need this to allow autofocus on input within Modal.
Before Modal would always steel focus after initial rendering of input.

Allow child element to start focus on Modal open

---

src/molecules/Menu/MobileMenu/MobileMenu.pcss

Without this the dropdown row looks slightly "lighter" in boldness compared to the other menu elements as can be seen in the screensot below.

Fix font-family to menu dropdown row

---

src/atoms/Box/Box.pcss
src/atoms/Button/Button.pcss
src/molecules/Avatar/Avatar.pcss
src/molecules/BigImageDialog/BigImageDialog.pcss
src/molecules/DropDownListWithLabel/DropDownListWithLabel.pcss
src/molecules/Dropdown/Dropdown.pcss
src/molecules/Menu/MenuCart.pcss
src/molecules/Menu/MobileMenu/MobileMenu.pcss

For iOS button has color -apple-system-blue. When running styleguide components on iOS default color is not black. Explicitly set color to black.

Override apple-system-blue for default html-tag value - set to black

---

src/atoms/Toggle/Toggle.pcss

Removed the z-index because it shows up on top of fixed footer when scrolling. Doesn't seem to be necessary to function as it should, but want to check if it was added for a specific reason? 😅

remove z- index on toggle thumb

---

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx
src/molecules/ShoppingCartV2/ShoppingCartItem.pcss

Also make price per unit wrap on small screens
Screens (image / icons)
Screens (price per unit wraps):

Fix image scaling for items

---

src/molecules/Breadcrumbs/Breadcrumbs.tsx
src/molecules/Footer/Footer.tsx
src/molecules/Menu/MobileMenu/MobileMenuItemWithDropdown.jsx

- arrow right was previously chevron, but latest Icons from voca has changed it

BreadCrumb and Mobile Main Menu: Use the chevron component instead of arrow right

---

src/molecules/Menu/MenuDropdown.pcss

Align menu dropdown with width of menu. 
Current:
New:

Align menu dropdown with menu

---

src/molecules/Breadcrumbs/Breadcrumbs.tsx

We're getting unnecessary warning when using this component, and this component already handles optional props.

Use BreadcrumbsProps already defined in file.

---

src/molecules/Header/Header.d.ts
src/molecules/Header/Header.jsx

Task NOCT-27694 requires `data-tracking-id` for various components and one of them is Header component. 
With this PR: 
- added the `dataTrackingID` prop to the Header component
- added the `data-tracking-id` attribute to the header element in the Header component

Add dataTrackingID to the Header component

---

src/atoms/Paragraph/Paragraph.d.ts
src/molecules/BoxGrid/BoxGrid.d.ts
src/molecules/Subscription/Subscription.d.ts

For Paragraph: We would like to use `id`
For BoxGrid: Added `className`
For Subscription: Added `isSelected`

Fix type declaration for Paragraph, BoxGrid and Subscription

---

src/molecules/Menu/MobileMenu/MobileMenuHeader.jsx

- added a fix that if one navigates between the Headings on mobile, it first just runs the "ItemSelected" without using the default rule of a tag (navigating)
- note: might be scenarios where one wants to follow the link on first click, but I have not seen any yet....

Bug: mobile menu redirects upon first clicking the "menu"

---

src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx

https://trello.com/c/a6E8Urf4/2926-styleguide-remove-usage-of-storybook-addon-knob
https://github.com/TeliaSoneraNorge/styleguide/pull/1316 removed the `@storybook/addon-knob` package, but not places where it is used. So all these ShoppingCart stories with `select()` gives an error at the moment.

Remove usage of @storybook/addon-knob

---

src/molecules/Modal/Modal.tsx

bugfix: On small screens, any click inside our outside the modal would close it, when it's fullscreen modal.
When size of the modal is fullscreen, we don't need that listener, so I disabled it.

fix(Modal): disable clickOutsideListener in case of fullscreen Modal

---

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss
src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx
src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx

https://trello.com/c/FVGv2weA/2960-make-ung-subscription-purple-background
- Removed `isInverted` prop and replaced it with a more general `variant` prop to also support purple variant. According to my research, webshop is the only team using the component and we don't actually use the inverted variant at the moment, so it should be fine.

SubscriptionCompactAccordion: Support purple variant

---

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss
src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx

https://trello.com/c/jeI3RS7u/3172-increase-margin-between-subscription-accordions
|---|---|
|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/6b7cdfbf-8d6f-4201-a1ec-a61b9db4ab8d)|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/114c0a26-bd40-472d-a220-269b7dbd9d7b)|

Increase margin between SubscriptionCompactAccordion

---

src/atoms/Button/Button.pcss
src/atoms/Button/Button.stories.tsx

After https://github.com/TeliaSoneraNorge/styleguide/pull/1425, I noticed that when adding `kind="voca-purple"`, the font-size in class `&--voca-normal` will override the font-size in `&--xs`.
I reordered them in the css file to change which takes priority.
|---|---|
|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/18a0e1c6-3a6c-444b-ac4e-01dd60508c8f)|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/186739eb-f899-4131-9433-53d26c603ed3)|

Button: Move style to change specificity

---

src/molecules/BigImageDialog/BigImageDialog.jsx
src/molecules/BigImageDialog/BigImageDialog.pcss

Removing center align so that topHeading will be aligned left.

BigImage D: Remove center align

---

src/molecules/Footer/Footer.tsx

https://trello.com/c/3H9wWODP/3382-unresponse-clicks-in-footer-menu
We have many Mediallia recordings showing that the footer links are unclickable on Android phones. Example:
https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/c52acb40-251a-4468-a5f4-e4a79b4d7bb2
This removes the disabled prop completely. It doesn't really matter that it is clickable on desktop as well since it will not expand on desktop.

Fix footer accordions on Android

---

README.md
VERSIONS.md
package-lock.json
package.json
postcss.config.js
src/molecules/DatePicker/Accessories.tsx
src/molecules/DatePicker/DataPicker.pcss
src/molecules/DatePicker/DatePicker.stories.tsx
src/molecules/DatePicker/DatePicker.tsx
src/molecules/DatePicker/DatePickerDay.tsx
src/molecules/DatePicker/DatePickerInput.tsx
src/molecules/DatePicker/types.ts
src/molecules/TextField/TextField.pcss
src/molecules/TextField/TextField.stories.tsx
src/molecules/TextField/TextField.tsx

- Datepicker inside `<form />` used to trigger form submit unnecessarily, because there were no `e.preventDefault()` in some callbacks or button did not have `type="text"`
- Removed  `postcss-custom-properties`. It was added 4 years ago and compiled css variables down to their values. But CSS variables have a wide brower support today, so there is no need to do that. 
- Extracted some component level css variables in order to enable theming datepicker and textinput locally in our project
- Added a paragraph about npm link
[draft pr at minside](https://github.com/telia-company/telia-no-min-side/pull/123)

enable css variables

---

src/molecules/Lozenge/Lozenge.tsx
src/molecules/ShoppingCartV2/ShoppingCart.stories.tsx
src/molecules/ShoppingCartV2/ShoppingCartItem.pcss
src/molecules/ShoppingCartV2/ShoppingCartItem.tsx
src/molecules/ShoppingCartV2/types.ts

https://trello.com/c/4UAnHy4R/4037-show-dobbel-data-in-cart
- Allow multiple lozenges in cart item
- Display them vertically both on mobile and desktop
|---|---|
|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/beb29bf4-86bf-49f4-a789-584d70ab6706)|![image](https://github.com/TeliaSoneraNorge/styleguide/assets/11172530/20544c5e-1e5c-40ac-92a6-a8e456bdf8ec)|

Allow multiple lozenges in cart item

---

src/molecules/Footer/Footer.pcss

WCAG requires minimum 24px height/width for clickable components.
Screen:

Adjust line height for min wcag size of clickable element

---

src/molecules/SideMenu/SideMenu.pcss
src/molecules/SideMenu/SideMenu.stories.tsx
src/molecules/SideMenu/SideMenuItem.tsx

We have a case where users don't have BankId of Temp access and therefore we want to limit their navigation through minside. Hence, we need to have a `disabled` state for SideMenuItem.

NOCT-3322: Add disabled prop for side menu

---

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss

CR fix for my initial commit where I added the styling in next project. Made it so that the purple and black ones do not lose their color when expanded and hovering (confirmed with Kristian)

fix: Remove light purple hover color

---

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss
src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx
src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx

Allow placing a suffix after price and allow placing priceStriketrough at end of line

Allow priceStriketrough at end

---

src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.pcss
src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.stories.tsx
src/molecules/SubscriptionCompactAccordion/SubscriptionCompactAccordion.tsx

Support dark-purple variant for SubscriptionCompactAccordion
